version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: strongrootpassword
      MYSQL_DATABASE: ShopApp
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: